language: python

python:
    - 3.7-dev
    - 3.6
    - 3.5
    - 3.4
    - 2.7

cache: pip

install: pip install coverage nose mock tox-travis

script: tox

after_success:
  - pip install codecov
  - codecov
